# EDA Million Verifier Data

In [1]:
import pandas as pd

In [2]:
raw_df = pd.read_csv('/home/blankpanda/Documents/code-workspaces/email-validator-web-app/data/Raw/Adage.csv')
raw_df.head()

,First Name,Last Name,Title,Company,Company Name for Emails,Email,Email Status,Email Confidence,Catch-all Status,Email Last Verified At,...,Last Raised At,Email Sent,Email Open,Email Bounced,Replied,Demoed,Number of Retail Locations,Apollo Contact Id,Apollo Account Id,User Managed
0,Aaron,Gaeir,CEO,GDX Studios,GDX Studios,agaeir+canned.response@gdxstudios.com,Verified,NaN,Catch-all,2024-06-28T05:51:34+00:00,...,NaN,NaN,False,False,False,False,NaN,6698e8d117be89000123c92b,6698e8d217be89000123cbee,True
1,Adam,Levine,New Business Consultant,Terri & Sandy,Terri & Sandy,adam@terrisandy.com,Verified,NaN,Not Catch-all,2024-07-18T09:25:18+00:00,...,NaN,NaN,False,False,False,False,NaN,6698e8d117be89000123c947,6698e8d217be89000123cbfa,True
2,NaN,NaN,NaN,Majority,Majority,adriana@majorityagency.com,Unverified,NaN,Not Catch-all,NaN,...,2023-06-01,NaN,False,False,False,False,NaN,6698e8d117be89000123c953,6698e8d217be89000123cbfc,True
3,Angela,Yu,Senior Designer,Koto,Koto,angela@koto.studio,Verified,NaN,Not Catch-all,2024-07-10T10:47:41+00:00,...,NaN,NaN,False,False,False,False,NaN,6698e8d117be89000123c9cb,6698e8d217be89000123cc05,True
4,NaN,NaN,NaN,Terri & Sandy,Terri & Sandy,ashley@terrisandy.com,Unverified,NaN,Not Catch-all,NaN,...,NaN,NaN,False,False,False,False,NaN,6698e8d117be89000123ca03,6698e8d217be89000123cbfa,True

In [3]:
first_1000_extract = raw_df[:1000]
first_1000_extract.to_csv("Adage_first_1000.csv", index=False)

# Clean Data

In [3]:
clean_df = pd.read_csv("/home/blankpanda/Documents/code-workspaces/email-validator-web-app/data/Cleaned/Adage_FULL_REPORT_MILLIONVERIFIER.COM.csv")
clean_df.head()

,First Name,Last Name,Title,Company,Company Name for Emails,Email,quality,result,free,role,...,Last Raised At,Email Sent,Email Open,Email Bounced,Replied,Demoed,Number of Retail Locations,Apollo Contact Id,Apollo Account Id,User Managed
0,Aaron,Gaeir,CEO,GDX Studios,GDX Studios,agaeir+canned.response@gdxstudios.com,risky,catch_all,no,no,...,NaN,NaN,False,False,False,False,NaN,6698e8d117be89000123c92b,6698e8d217be89000123cbee,True
1,Adam,Levine,New Business Consultant,Terri & Sandy,Terri & Sandy,adam@terrisandy.com,bad,invalid,no,no,...,NaN,NaN,False,False,False,False,NaN,6698e8d117be89000123c947,6698e8d217be89000123cbfa,True
2,NaN,NaN,NaN,Majority,Majority,adriana@majorityagency.com,bad,invalid,no,no,...,2023-06-01,NaN,False,False,False,False,NaN,6698e8d117be89000123c953,6698e8d217be89000123cbfc,True
3,Angela,Yu,Senior Designer,Koto,Koto,angela@koto.studio,good,ok,no,no,...,NaN,NaN,False,False,False,False,NaN,6698e8d117be89000123c9cb,6698e8d217be89000123cc05,True
4,NaN,NaN,NaN,Terri & Sandy,Terri & Sandy,ashley@terrisandy.com,good,ok,no,no,...,NaN,NaN,False,False,False,False,NaN,6698e8d117be89000123ca03,6698e8d217be89000123cbfa,True

In [ ]:


Email: ashley@terrisandy.com
User: ashley
Domain: terrisandy.com
Smtp_check: true
Mx_found: true
Role: false
Disposable: false
Score: 0.8
State: deliverable
Reason: valid_mailbox
Free: false
Format_valid: true
Catch_all: null


Email: adam@terrisandy.com
User: adam
Domain: terrisandy.com
Smtp_check: false
Mx_found: true
Role: false
Disposable: false
Score: 0.64
State: undeliverable
Reason: invalid_mailbox
Free: false
Format_valid: true
Catch_all: null


{
  "tag": "canned.response",
  "free": false,
  "role": false,
  "user": "agaeir+canned.response",
  "email": "agaeir+canned.response@gdxstudios.com",
  "score": 0.8,
  "state": "deliverable",
  "domain": "gdxstudios.com",
  "reason": "valid_mailbox",
  "mx_found": true,
  "catch_all": null,
  "disposable": false,
  "smtp_check": true,
  "did_you_mean": "",
  "format_valid": true
}